# Generated by Django 6.0.5 on 2026-07-02 22:15

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_friendship_blocked_at_alter_friendship_status_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='friendship',
            name='accepted_at',
        ),
        migrations.RemoveField(
            model_name='friendship',
            name='removed_at',
        ),
        migrations.RemoveField(
            model_name='friendship',
            name='status',
        ),
        migrations.AddField(
            model_name='friendship',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
