# Generated by Django 6.0.5 on 2026-07-02 22:25

from django.db import migrations, models
from django.db.models import F, Q
from django.conf import settings


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_friendship_accepted_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='usercontentpermission',
            name='unique_permission',
        ),
        migrations.RemoveConstraint(
            model_name='usercontentpermission',
            name='owner_not_target_user',
        ),
        migrations.RemoveField(
            model_name='usercontentpermission',
            name='applies_to',
        ),
        migrations.RenameField(
            model_name='usercontentpermission',
            old_name='target_user',
            new_name='grantee',
        ),
        migrations.AlterField(
            model_name='usercontentpermission',
            name='grantee',
            field=models.ForeignKey(on_delete=models.deletion.CASCADE, related_name='granted_content_permissions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddConstraint(
            model_name='usercontentpermission',
            constraint=models.UniqueConstraint(fields=('owner', 'grantee'), name='unique_content_permission'),
        ),
        migrations.AddConstraint(
            model_name='usercontentpermission',
            constraint=models.CheckConstraint(condition=~Q(owner=F('grantee')), name='owner_not_grantee'),
        ),
    ]
