# Generated by Django 6.0.5 on 2026-07-02 22:30

import django.db.models.deletion
from django.db import migrations, models


def delete_legacy_friend_request_events(apps, schema_editor):
    FriendRequestEvent = apps.get_model('accounts', 'FriendRequestEvent')
    FriendRequestEvent.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_align_user_content_permission'),
    ]

    operations = [
        migrations.RunPython(
            delete_legacy_friend_request_events,
            migrations.RunPython.noop,
        ),
        migrations.RemoveField(
            model_name='friendrequestevent',
            name='friendship',
        ),
        migrations.AddField(
            model_name='friendrequestevent',
            name='action',
            field=models.CharField(choices=[('sent', 'Sent'), ('accepted', 'Accepted'), ('declined', 'Declined'), ('cancelled', 'Cancelled')], default='sent', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='friendrequestevent',
            name='friend_request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='accounts.friendrequest'),
        ),
    ]
