# Generated by Django 6.0.5 on 2026-07-03 00:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0006_revisiontopic'),
        ('planning', '0002_repair_stale_planning_tables'),
    ]

    operations = [
        migrations.AddField(
            model_name='studysession',
            name='module',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='academics.module'),
        ),
    ]
