# Generated by Django 6.0.5 on 2026-07-03 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0005_alter_calendarevent_colour_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TimetableImport',
        ),
    ]
