# Generated by Django 6.0.5 on 2026-07-03 21:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0006_delete_timetableimport'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='scheduled_for',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='TaskRecurrence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequency', models.CharField(choices=[('D', 'Daily'), ('W', 'Weekly'), ('M', 'Monthly')], max_length=1)),
                ('interval', models.PositiveSmallIntegerField(default=1)),
                ('starts_at', models.DateTimeField()),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('next_occurrence_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('template_task', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='recurrence_rule', to='planning.task')),
            ],
        ),
        migrations.AddField(
            model_name='task',
            name='recurrence',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='occurrences', to='planning.taskrecurrence'),
        ),
        migrations.AddConstraint(
            model_name='task',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('recurrence__isnull', True), ('scheduled_for__isnull', True)), models.Q(('recurrence__isnull', False), ('scheduled_for__isnull', False)), _connector='OR'), name='task_recurrence_fields_together'),
        ),
        migrations.AddConstraint(
            model_name='task',
            constraint=models.UniqueConstraint(condition=models.Q(('recurrence__isnull', False)), fields=('recurrence', 'scheduled_for'), name='task_unique_recurrence_slot'),
        ),
        migrations.AddConstraint(
            model_name='taskrecurrence',
            constraint=models.CheckConstraint(condition=models.Q(('interval__gte', 1)), name='taskrecurrence_interval_gte_1'),
        ),
        migrations.AddConstraint(
            model_name='taskrecurrence',
            constraint=models.CheckConstraint(condition=models.Q(('ends_at__isnull', True), ('ends_at__gte', models.F('starts_at')), _connector='OR'), name='taskrecurrence_end_gte_start'),
        ),
        migrations.AddConstraint(
            model_name='taskrecurrence',
            constraint=models.CheckConstraint(condition=models.Q(('next_occurrence_at__isnull', True), ('next_occurrence_at__gte', models.F('starts_at')), _connector='OR'), name='taskrecurrence_next_gte_start'),
        ),
        migrations.AddConstraint(
            model_name='taskrecurrence',
            constraint=models.CheckConstraint(condition=models.Q(('next_occurrence_at__isnull', True), ('ends_at__isnull', True), ('next_occurrence_at__lte', models.F('ends_at')), _connector='OR'), name='taskrecurrence_next_lte_end'),
        ),
    ]
