# Generated by Django 6.0.6 on 2026-07-03 02:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('content', '0009_whiteboard'),
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StoredFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='files')),
                ('mime_type', models.CharField(max_length=255)),
                ('size', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='FilePreview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('preview_url', models.URLField(null=True)),
                ('status', models.CharField(choices=[('pending', 'PENDING'), ('generated', 'GENERATED'), ('failed', 'FAILED')], default='pending', max_length=9)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stored_file', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='files.storedfile')),
            ],
        ),
        migrations.CreateModel(
            name='FileVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.PositiveIntegerField()),
                ('file', models.FileField(upload_to='files')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('stored_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='files.storedfile')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('stored_file', 'version_number'), name='unique_file_version')],
            },
        ),
        migrations.CreateModel(
            name='FileTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.tag')),
                ('stored_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='files.storedfile')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('stored_file', 'tag'), name='unique_tag')],
            },
        ),
        migrations.CreateModel(
            name='FileShare',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission', models.CharField(choices=[('view', 'VIEW'), ('edit', 'EDIT'), ('download', 'DOWNLOAD'), ('delete', 'DELETE')], max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('stored_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='files.storedfile')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('stored_file', 'user'), name='unique_share')],
            },
        ),
        migrations.CreateModel(
            name='FileLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('stored_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='files.storedfile')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('stored_file', 'content_type', 'object_id'), name='unique_link')],
            },
        ),
    ]
