# Generated by Django 6.0.6 on 2026-07-03 03:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0010_note_collection_whiteboard_collection'),
        ('files', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='filelink',
            name='stored_file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='files.storedfile'),
        ),
        migrations.AlterField(
            model_name='filepreview',
            name='preview_url',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='filepreview',
            name='stored_file',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='preview', to='files.storedfile'),
        ),
        migrations.AlterField(
            model_name='fileshare',
            name='stored_file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shares', to='files.storedfile'),
        ),
        migrations.AlterField(
            model_name='fileshare',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_shares', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='filetag',
            name='stored_file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_tags', to='files.storedfile'),
        ),
        migrations.AlterField(
            model_name='filetag',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_tags', to='content.tag'),
        ),
        migrations.AlterField(
            model_name='fileversion',
            name='stored_file',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='files.storedfile'),
        ),
        migrations.AlterField(
            model_name='storedfile',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stored_files', to=settings.AUTH_USER_MODEL),
        ),
    ]
