# Generated by Django 6.0.5 on 2026-07-03 02:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collaboration', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GroupMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('member', 'Member'), ('owner', 'Owner')], default='member', max_length=10)),
                ('status', models.CharField(choices=[('active', 'Active'), ('invited', 'Invited'), ('left', 'Left')], default='active', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('study_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='collaboration.studygroup')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'study_group'), name='unique_membership')],
            },
        ),
    ]
