# Generated by Django 6.0.5 on 2026-07-03 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collaboration', '0007_discussionmessage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('direct', 'Direct'), ('group', 'Group')], max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
