# Generated by Django 6.0.5 on 2026-07-03 02:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SearchHistoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.TextField()),
                ('filters', models.JSONField(blank=True, null=True)),
                ('result_count', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SearchSynonym',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(max_length=100)),
                ('synonym', models.CharField(max_length=100)),
                ('scope', models.CharField(choices=[('global', 'Global'), ('academics', 'Academics'), ('content', 'Content'), ('files', 'Files'), ('planning', 'Planning'), ('accounts', 'Accounts'), ('collaboration', 'Collaboration')], max_length=100)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('active', True)), fields=('term', 'synonym'), name='unique_term')],
            },
        ),
        migrations.CreateModel(
            name='SavedSearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('query', models.TextField()),
                ('filters', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'name'), name='unique_user_to_name')],
            },
        ),
        migrations.CreateModel(
            name='SearchIndexEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_app_label', models.CharField(max_length=100)),
                ('source_object_type', models.CharField(max_length=100)),
                ('source_object_id', models.PositiveIntegerField()),
                ('title', models.TextField()),
                ('summary', models.TextField()),
                ('keywords', models.TextField()),
                ('visibility', models.CharField(choices=[('P', 'PUBLIC'), ('S', 'SHARED'), ('G', 'GROUP')], max_length=100)),
                ('last_indexed', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('source_app_label', 'source_object_type', 'source_object_id'), name='source_app_label_name_source_object_type_source_object_id')],
            },
        ),
    ]
