# Generated by Django 6.0.5 on 2026-07-03 01:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='NoteLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('note', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='note_links', to='content.note')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('note', 'content_type', 'object_id'), name='note_link_unique')],
            },
        ),
    ]
