# Generated by Django 6.0.6 on 2026-07-03 03:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0009_whiteboard'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='collection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notes', to='content.contentcollection'),
        ),
        migrations.AddField(
            model_name='whiteboard',
            name='collection',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='whiteboards', to='content.contentcollection'),
        ),
    ]
