# Generated by Django 6.0.5 on 2026-07-02 23:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('code', models.CharField(blank=True, max_length=20, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('colour', models.CharField(blank=True, max_length=6, null=True)),
                ('academic_year', models.CharField(blank=True, max_length=9, null=True)),
                ('semester', models.CharField(blank=True, choices=[('autumn', 'Autumn'), ('spring', 'Spring'), ('summer', 'Summer'), ('full_year', 'Full Year')], max_length=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owned_modules', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
