# Generated by Django 6.0.5 on 2026-07-02 23:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0003_lecture'),
    ]

    operations = [
        migrations.CreateModel(
            name='TimetableEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.CharField(choices=[('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday'), ('saturday', 'Saturday'), ('sunday', 'Sunday')], max_length=10)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('room', models.CharField(blank=True, max_length=100, null=True)),
                ('recurrence_type', models.CharField(choices=[('once', 'once'), ('daily', 'Daily'), ('weekly', 'Weekly'), ('fortnightly', 'Fortnightly')], default='once', max_length=20)),
                ('date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lecture', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='timetable_entries', to='academics.lecture')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetable_entries', to='academics.module')),
            ],
        ),
    ]
