# Generated by Django 6.0.5 on 2026-07-03 00:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0004_timetableentry'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('deadline', models.DateTimeField(blank=True, null=True)),
                ('weighting', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('submission_type', models.CharField(blank=True, choices=[('essay', 'Essay'), ('report', 'Report'), ('presentation', 'Presentation'), ('exam', 'Exam'), ('practical', 'Practical'), ('other', 'Other')], max_length=20, null=True)),
                ('is_group', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('submitted', 'Submitted'), ('completed', 'Completed')], default='not_started', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='academics.module')),
            ],
        ),
    ]
