# Generated by Django 6.0.5 on 2026-07-03 00:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0004_timetableentry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timetableentry',
            name='day_of_week',
            field=models.CharField(choices=[('mon', 'Monday'), ('tue', 'Tuesday'), ('wed', 'Wednesday'), ('thu', 'Thursday'), ('fri', 'Friday'), ('sat', 'Saturday'), ('sun', 'Sunday')], max_length=10),
        ),
        migrations.AlterField(
            model_name='timetableentry',
            name='lecture',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='timetable_entries', to='academics.lecture'),
        ),
        migrations.AlterField(
            model_name='timetableentry',
            name='recurrence_type',
            field=models.CharField(choices=[('weekly', 'Weekly'), ('fortnightly', 'Fortnightly'), ('one_off', 'One-off')], default='weekly', max_length=20),
        ),
    ]
