# Generated by Django 6.0.5 on 2026-07-03 00:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0005_assignment'),
    ]

    operations = [
        migrations.CreateModel(
            name='RevisionTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('confidence', models.CharField(blank=True, choices=[('red', 'Red'), ('amber', 'Amber'), ('green', 'Green')], max_length=10, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='revision_topics', to='academics.module')),
            ],
        ),
    ]
