# Generated by Django 6.0.6 on 2026-07-03 03:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0006_revisiontopic'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lecture',
            old_name='notes',
            new_name='description',
        ),
    ]
