# Generated by Django 6.0.5 on 2026-07-03 16:58

from django.db import migrations, models


def update_submission_statuses(apps, schema_editor):
    Assignment = apps.get_model("academics", "Assignment")

    Assignment.objects.filter(
        submission_status__in=["not_started", "in_progress"]
    ).update(submission_status="not_submitted")

    Assignment.objects.filter(
        submission_status__in=["submitted", "completed"]
    ).update(submission_status="submitted")


class Migration(migrations.Migration):

    dependencies = [
        ("academics", "0008_timetableimport"),
    ]

    operations = [
        migrations.RenameField(
            model_name="assignment",
            old_name="status",
            new_name="submission_status",
        ),
        migrations.RunPython(
            update_submission_statuses,
            migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name="assignment",
            name="submission_status",
            field=models.CharField(
                choices=[
                    ("not_submitted", "Not Submitted"),
                    ("submitted", "Submitted"),
                ],
                default="not_submitted",
                max_length=20,
            ),
        ),
    ]
