# Generated by Django 6.0.5 on 2026-07-04 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0010_assignmentparticipant_assignment_participants'),
    ]

    operations = [
        migrations.AddField(
            model_name='timetableentry',
            name='is_manually_edited',
            field=models.BooleanField(default=False),
        ),
    ]
