# Generated by Django 6.0.6 on 2026-07-02 17:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('AR', 'Assignment Reminder'), ('LR', 'Lecture Reminder'), ('CR', 'Calendar Reminder'), ('GU', 'Group Update'), ('FR', 'Friend Request'), ('NM', 'New Message'), ('SSI', 'Study Session Invite')], max_length=3)),
                ('title', models.CharField(max_length=120)),
                ('body', models.TextField()),
                ('source_app', models.CharField(max_length=120)),
                ('source_object_type', models.CharField(max_length=120)),
                ('source_object_id', models.PositiveIntegerField()),
                ('read_at', models.DateTimeField(null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('actor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_actor_fk', to=settings.AUTH_USER_MODEL)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='noticication_recipient_fk', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MutedContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_app', models.CharField(max_length=120)),
                ('source_object_type', models.CharField(max_length=120)),
                ('source_object_id', models.PositiveIntegerField()),
                ('muted_until', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='muted_content', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'source_app', 'source_object_type', 'source_object_id'), name='unique_mute_per_user_and_source')],
            },
        ),
        migrations.CreateModel(
            name='NotificationDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('A', 'All'), ('T', 'Text'), ('E', 'Email'), ('D', 'Discord'), ('I', 'In App')], max_length=100)),
                ('status', models.CharField(choices=[('P', 'Pending'), ('S', 'Sent'), ('F', 'Failed'), ('SK', 'Skipped')], max_length=100)),
                ('attempted_at', models.DateTimeField(auto_now_add=True)),
                ('provider_response', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery', to='notifications.notification')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('notification', 'channel'), name='unique_notification_delivery')],
            },
        ),
        migrations.CreateModel(
            name='NotificationPreferences',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('AR', 'Assignment Reminder'), ('LR', 'Lecture Reminder'), ('CR', 'Calendar Reminder'), ('GU', 'Group Update'), ('FR', 'Friend Request'), ('NM', 'New Message'), ('SSI', 'Study Session Invite')], max_length=100)),
                ('channel', models.CharField(choices=[('A', 'All'), ('T', 'Text'), ('E', 'Email'), ('D', 'Discord'), ('I', 'In App')], max_length=100)),
                ('enabled_flag', models.BooleanField(default=True)),
                ('quiet_hours_start', models.TimeField()),
                ('quiet_hours_end', models.TimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('user', 'category', 'channel'), name='unique_notification_perferences')],
            },
        ),
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_app', models.CharField(max_length=120)),
                ('source_object_type', models.CharField(max_length=120)),
                ('source_object_id', models.PositiveIntegerField()),
                ('remind_at', models.DateTimeField()),
                ('status', models.CharField(choices=[('P', 'Pending'), ('S', 'Sent'), ('C', 'Canceled')], max_length=120)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminder_recipient_fk', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('recipient', 'source_app', 'source_object_type', 'source_object_id', 'remind_at'), name='unique_reminder')],
            },
        ),
    ]
