# Generated by Django 6.0.6 on 2026-07-03 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_remove_notificationpreferences_unique_notification_perferences_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationdelivery',
            name='status',
            field=models.CharField(choices=[('P', 'Pending'), ('S', 'Sent'), ('C', 'Canceled'), ('SK', 'Skipped')], max_length=100),
        ),
    ]
