# Generated by Django 6.0.6

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_alter_notificationdelivery_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='category',
            field=models.CharField(choices=[('assignment_reminder', 'Assignment Reminder'), ('lecture_reminder', 'Lecture Reminder'), ('calendar_reminder', 'Calendar Reminder'), ('group_update', 'Group Update'), ('friend_request', 'Friend Request'), ('new_message', 'New Message'), ('study_session_invite', 'Study Session Invite')], max_length=25),
        ),
    ]
