# Generated by Django 6.0.5 on 2026-07-03 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0006_repair_source_reference_naming'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notificationdelivery',
            name='channel',
            field=models.CharField(choices=[('all', 'All'), ('text', 'Text'), ('emial', 'Email'), ('discord', 'Discord'), ('in_app', 'In App')], max_length=100),
        ),
        migrations.AlterField(
            model_name='notificationdelivery',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('canceled', 'Canceled'), ('skipped', 'Skipped')], max_length=100),
        ),
        migrations.AlterField(
            model_name='notificationpreferences',
            name='category',
            field=models.CharField(choices=[('assignment_reminder', 'Assignment Reminder'), ('lecture_reminder', 'Lecture Reminder'), ('calendar_reminder', 'Calendar Reminder'), ('group_update', 'Group Update'), ('friend_request', 'Friend Request'), ('new_message', 'New Message'), ('study_session_invite', 'Study Session Invite')], max_length=100),
        ),
        migrations.AlterField(
            model_name='notificationpreferences',
            name='channel',
            field=models.CharField(choices=[('all', 'All'), ('text', 'Text'), ('emial', 'Email'), ('discord', 'Discord'), ('in_app', 'In App')], max_length=100),
        ),
        migrations.AlterField(
            model_name='reminder',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('sent', 'Sent'), ('canceled', 'Canceled')], max_length=120),
        ),
    ]
